app:
  version: 0.0.1
  namespace: Caracal

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

server:
  port: 8070
  ssl:
    enabled: true
    certificate: certs/site/master/caracal-dev.crt
    certificate-private-key: certs/site/master/caracal-dev.key

jwt:
  secret: E9uH8R48vrqZdCaf

spring:
  application:
    name: Apache Camel - Integration Framework
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
     allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

camel:
  springboot:
    name: caracal-camel
    routes-reload-enabled: true
    routes-include-pattern: classpath:camel-routes/*
    routes-reload-directory: classpath:camel-routes
    route-controller-supervise-enabled: true
    route-shutdown-delay: 5000
  component:
    http:
      use-global-ssl-context-parameters: true

    mybatis:
      config-location: classpath:ibatis/mybatis-config.xml
      mapper-locations: classpath*:ibatis/mappers/*.xml
      type-aliases-package: com.caracal.camel.routes.models





# https://www.baeldung.com/spring-boot-https-self-signed-certificate
# certs/site/master/
# keytool -import -alias dev.divigraph.com -file certs/divigraph-dev.pem -keystore /usr/java/latest/lib/security/cacerts
# run in admin mode https://www.tutorialworks.com/java-trust-ssl/
#keytool -import -alias dev.caracal.com -file certs/site/master/caracal-dev.pem -keystore "C:\Program Files\Java\jdk-19\lib\security\cacerts"
#keytool -import -alias dev.caracal.com -file  certs/site/master/caracal-dev.pem -keystore "C:\Program Files\Java\jdk-20\lib\security\cacerts"

#keytool -import -alias dev.caracal.com -file certs/site/master/caracal-dev.pem -keystore /Users/ettienemare/Library/Java/JavaVirtualMachines/openjdk-20/Contents/Home/lib/security/cacerts