server:
  port: 8070
  ssl:
    enabled: true
    key-store-type: JKS
    keystore: classpath:certs/hivemq.jks
    key-store-password: E9uH8R48vrqZdCaf
    #trust-store-type: JKS
    #trust-store: classpath:certs/hivemq-trust-store.jks
    #trust-store-password: hgcmgThgYhVGz5bW

spring:
  application:
    name: Caracal Demo
  main:
     allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

camel:
  springboot:
    routes-reload-enabled: true
    routes-include-pattern: classpath:camel-routes/*
    routes-reload-directory: classpath:camel-routes
    route-controller-supervise-enabled: true
    route-shutdown-delay: 5000



  component:
    http:
      use-global-ssl-context-parameters: true
# https://www.baeldung.com/spring-boot-https-self-signed-certificate