app:
  version: 0.0.1

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

server:
  port: 8070
  ssl:
    enabled: true
    certificate: certs/divigraph-dev.crt
    certificate-private-key: certs/divigraph-dev.key

jwt:
  secret: E9uH8R48vrqZdCaf

spring:
  application:
    name: Caracal Demo
  main:
     allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

camel:
  springboot:
    name: caracal-camel
    routes-reload-enabled: true
    routes-include-pattern: classpath:camel-routes/*
    routes-reload-directory: classpath:camel-routes
    route-controller-supervise-enabled: true
    route-shutdown-delay: 5000
  component:
    http:
      use-global-ssl-context-parameters: true
# https://www.baeldung.com/spring-boot-https-self-signed-certificate

# run in admin mode https://www.tutorialworks.com/java-trust-ssl/
#keytool -import -alias dev.divigraph.com -file certs/divigraph-dev.pem -keystore "C:\Program Files\Java\jdk-19\lib\security\cacerts"
#keytool -import -alias dev.divigraph.com -file certs/divigraph-dev.pem -keystore "C:\Users\EttieneMare\.jdks\openjdk-19.0.2\lib\security\cacerts"
#keytool -import -alias dev.divigraph.com -file certs/divigraph-dev.pem -keystore /Users/ettienemare/Library/Java/JavaVirtualMachines/openjdk-19.0.2/Contents/Home/lib/security/cacerts
#keytool -import -alias dev.divigraph.com -file certs/divigraph-dev.pem -keystore /Users/ettienemare/Library/Java/JavaVirtualMachines/openjdk-20/Contents/Home/lib/security/cacerts