{
 "title": "Camel dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "MQTT Client to Cloud Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(CamelExchangesFailed_total{routeId=\"xml-client-cloud\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(CamelExchangeEventNotifier_seconds_count{eventType=\"ExchangeFailedEvent\"}[45s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Client to Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(CamelExchangesSucceeded_total{routeId=\"xml-client-cloud\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Server to Cloud",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(CamelExchangesSucceeded_total{routeId=\"xml-client-cloud\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Server To Cloud (Failure)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(CamelExchangesFailed_total{routeId=\"xml-client-cloud\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}