{
 "title": "Camel Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MQTT Client to Cloud Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(CamelExchangesFailuresHandled_total{routeId=\"xml-client-cloud\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Server to Cloud",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(CamelExchangesSucceeded_total{routeId=\"xml-client-cloud\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Server To Cloud (Failure)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(CamelExchangesFailuresHandled_total{routeId=\"xml-client-cloud\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Client to Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(CamelExchangesSucceeded_total{routeId=\"xml-client-cloud\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}