version: "3.9"
name: caracal-camel

services:
  caracal-camel:
    container_name: caracal-camel
    build:
      context: ..
      dockerfile: Dockerfile
    image: caracal/camel
    ports:
      - "8070:8070"
    volumes:
      - ../data:/app/data
      - ../certs:/certs
    networks:
      - caracal-network
    depends_on:
      hivemq-server:
        condition: service_started
      hivemq-cloud:
        condition: service_started

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/certs/divigraph-dev.crt:/certs/divigraph-dev.crt
      - ./prometheus/certs/divigraph-dev.key:/certs/divigraph-dev.key
    networks:
      - caracal-network

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ../certs/site/master/caracal-dev.crt:/etc/grafana/grafana.crt
      - ../certs/site/master/caracal-dev.key:/etc/grafana/grafana.key
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - caracal-network

  hivemq-server:
    image: hivemq/hivemq-ce:latest-arm64v8
    container_name: hivemq-server
    deploy:
      resources:
        limits:
          memory: 800M
    mem_reservation: 800M
    ports:
      - "1883:1883"
      - "8081:8080"
      - "8883:8883"
      - "9399:9399"
    volumes:
      - ./hivemq/server/conf:/opt/hivemq/conf
      - ./hivemq/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
      - ../certs/hivemq/certs/default:/certs
    networks:
      - caracal-network
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"

  hivemq-cloud:
    container_name: hivemq-cloud
    image: hivemq/hivemq-ce:latest-arm64v8
    deploy:
      resources:
        limits:
          memory: 800M
    mem_reservation: 800M
    ports:
      - "1884:1883"
      - "8084:8080"
      - "2884:8883"
    volumes:
      - ./hivemq/cloud/conf:/opt/hivemq/conf
      - ./hivemq/hivemq-prometheus-extension:/opt/hivemq/extensions/hivemq-prometheus-extension
      - ../certs/hivemq/certs/cloud:/certs
    networks:
      - caracal-network
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"

networks:
  caracal-network:
    driver: bridge